thelawcentresnetwork/lcn-design-system

package-lock.json
package.json
src/components/Banner.tsx
src/components/Card.tsx
src/components/DynamicForm/Checkbox.tsx
src/components/DynamicForm/Date.tsx
src/components/DynamicForm/Input.tsx
src/components/DynamicForm/Number.tsx
src/components/DynamicForm/Radio.tsx
src/components/DynamicForm/Select.tsx
src/components/DynamicForm/Textarea.tsx
src/components/Quote.tsx
src/patterns/FormBuilder/Field.jsx

Related to this issue: [#41](https://github.com/thelawcentresnetwork/lcn_ems/issues/41)

Make dselect test work

---

.github/workflows/npm-publish.yml

chore: update npm-publish.yml

---

src/atoms/Typography/Typography.stories.mdx
src/theme/foundations/fonts.js

Adds body and subtitle text to typography story in the design system.
It also moves the typography story to the atoms folder

style: add remaining body styles to typography

---

src/theme/components/Button.js
src/theme/index.js

This uses the modern Chakra UI recommended way to style components

Refactor button theme style

---

package-lock.json
package.json
src/components/Button/Button.mdx
src/components/Button/Button.stories.tsx
src/theme/components/Button.js

Fixes icon button styling that broke after I added default button styles because icon buttons use those as default. 
Picture of the bug:

Fix icon buttons

---

babel.config.js
package-lock.json
package.json
src/components/Hero/HomepageHero/HomepageHero.stories.tsx
src/components/Hero/HomepageHero/HomepageHero.tsx

The babel plugin didn't work, so to avoid this issue we will require an image be specified instead.

fix: make HomepageHero have a required img prop

---

src/components/Hero/HomepageHero/HomepageHero.stories.tsx
src/components/Hero/HomepageHero/HomepageHero.tsx

Realised I hadn't made the button a link and it wasn't conditionally rendered.

fix: turn button into a link

---

src/components/Hero/PageHero/Hero.stories.tsx
src/theme/components/Menu.js
src/theme/foundations/colors.d.ts

adds the dropdown colours for the page hero: https://github.com/thelawcentresnetwork/lcn-design-system/issues/44#event-9755085979
removes the border from the navigation dropdown menu for: https://github.com/thelawcentresnetwork/lcn_website/issues/11#event-9755082740

Fixes from testing

---

src/components/Forms/InputFields/InputFields.mdx
src/components/Forms/InputFields/InputFields.stories.tsx
src/theme/components/Input.js

Issue: https://github.com/thelawcentresnetwork/lcn-design-system/issues/68

Add outline input variant

---

src/patterns/GetHelp/GetHelp.stories.tsx
src/patterns/GetHelp/GetHelp.tsx
src/patterns/GetHelp/LawCentreDetails/LawCentreDetails.stories.tsx
src/patterns/GetHelp/LawCentreDetails/LawCentreDetails.tsx
src/patterns/GetHelp/NoResults/NoResults.stories.tsx
src/patterns/GetHelp/NoResults/NoResults.tsx
src/patterns/GetHelp/Results/Results.stories.tsx
src/patterns/GetHelp/Results/Results.tsx
src/patterns/GetHelp/Search/Search.stories.tsx
src/patterns/GetHelp/Search/Search.tsx
src/theme/components/Button.js
src/theme/foundations/globalStyles.js

This is the first part of work adding the get help flow. 
Just responsive styling for the separate components for now. The actual flow is currently showing all stages.
Also fixes buttons not being responsive.

Add get help pattern

---

src/atoms/Typography/Typography.stories.mdx
src/theme/components/List.js
src/theme/index.js

I did a thing! Added basic list styling. Not 100% like designs but near enough for now.

Update list styling

---

src/patterns/GetHelp/GetHelp.stories.tsx
src/patterns/GetHelp/GetHelp.tsx
src/patterns/GetHelp/GetHelp.types.tsx
src/patterns/GetHelp/LawCentreDetails/LawCentreDetails.tsx
src/patterns/GetHelp/Results/Results.tsx

Work to calculate the nearest law centre based on a users location and latitude and longitude of law centres.
Uses dummy data for now (branch name is a bit ambitious)
Also, adds props to component so LCN can change the "warning text".

Find nearest law centre

---

src/atoms/Section/Section.mdx
src/atoms/Section/Section.stories.tsx
src/atoms/Section/Section.tsx
src/index.jsx

Add section

---

src/atoms/Callout/Callout.mdx
src/atoms/Callout/Callout.stories.tsx
src/atoms/Callout/Callout.tsx
src/index.jsx

feat: add callout

---

src/index.jsx

add correct import

---

src/atoms/Callout/Callout.stories.tsx
src/atoms/Callout/Callout.tsx
src/components/Image/Image.tsx

Fixes the callout so that children can be passed into it- this will allow rich text editor to be passed into it into the jamstack
Also fixes the image so that it does not fill up the entire screen (by turning it from flex to box)

Fixes for image and callout

---

src/theme/components/Menu.js

fix the border radius on dropdown

fix: border radius on menu dropdown

---

src/components/Cards/Cards.tsx

Makes the title on the news card a link

fix: news home page cards

---

src/components/Hero/HomepageHero/HomepageHero.stories.tsx
src/components/Hero/HomepageHero/HomepageHero.tsx

fix: hero heading had not alt text

---

src/atoms/Icons/Icons.tsx
src/components/Cards/Card.stories.tsx
src/components/Cards/Cards.tsx
src/components/LatestNews/LatestNews.tsx

Download file feature

---

src/components/LatestNews/LatestNews.tsx

Fixes excessive padding on the latest news section, and also switches the visual flair so it matches the designs.

fix: visual flair and padding on latest news

---

src/atoms/Callout/Callout.tsx

Switches the extended visual flairs so that they match what is on the page designs

fix: callout flair and padding

---

src/atoms/Section/Section.tsx

Removes the extra margin on the page hero, and reduces padding top

fix: padding and margin on sections

---

src/atoms/Icons/Icons.tsx
src/index.jsx

This PR adds the following icon to the design system. Since all other arrows icons have been added this ensures consistency across the repositories.

Add Icon For Link

---

src/components/Feature/Feature.stories.tsx
src/components/Feature/Feature.tsx

…the Feature as tested in Chrome

Add centre option to Feature which creates an auto-margin

---

package.json
src/atoms/Icons/Icons.tsx
src/atoms/Section/Section.tsx
src/components/Cards/Cards.tsx
src/components/Hero/HomepageHero/HomepageHero.tsx
src/components/Hero/PageHero/Hero.tsx
src/components/LatestNews/LatestNews.tsx
src/theme/foundations/colors.js

* Create getColor funciton
* Update icons for icon-link component
* Make news megaphone smaller
* Tumbling card decoration (relates to lcn-jamstack as well)
* Homepage hero CTA button improvements
* Improvements to homepage hero font styling
* Improve hero subheading font size in line with designs
* Fix space in slanted section decoration
* Card: Place link on entire card — make entire card clickable
* Improve hero subheading text in line with designs
* Card: Both lines on 2-line titles aligned with each other fix
* Improve image in cards to use objectFit and chakra component
* Card: Attempt to fix variable sizing
* Update version number to 3.0.42

Design system snagging
